### ISSUE TITLE
SingleR book site not found

### ISSUE THREAD

**Issue by Lucyyang1991** [SingleR-inc/SingleR#251]
Thanks so much for the effort in this great package, but recently I can't read the singleR book anymore.
I use this 'https://ltla.github.io/SingleRBook/'.
Can you solve this problem?

**Comment by PeteHaitch** [comment]
The published book was moved to https://bioconductor.org/books/release/SingleRBook.html but there are currently some errors in building the book (see https://support.bioconductor.org/p/9155397/#9155398).

**Comment by LTLA** [comment]
Turns out there was a PR about this quite some time ago (LTLA/SingleRBook#1), that I never noticed because I never get notification about book failures. Once that gets merged, the book should come back. Hopefully.

**Comment by j-andrews7** [comment]
This seems resolved.
