### ISSUE TITLE
Fix some plot-related warnings in the tests

### ISSUE THREAD

**Issue by LTLA** [SingleR-inc/SingleR#276]
@dtm2451 can you have a look at some of the warnings in the plotting code? Not critical as the tests still pass, but you never know - I also did some major changes to the underlying code, so the warnings might be picking up something that the other tests didn't see.

(Check out the NEWS file for the scope of the changes. Results should largely be unaffected though there are a few minor changes due to differences in how we break ties between markers.)

**Comment by dtm2451** [comment]
The 4/5 from test-heatmap.R are our own totally expected, and tested, warnings where I should have cleaned this clutter from the tests previously... maybe they weren't reported in a past version, but easy enough to make go away without hurting anything.
The last one from test-score-dist.R indicates I didn't update the plotting code around ggplot's removal of aes_string between v2->v3.  Also easy to fix.

PR incoming

**Comment by LTLA** [comment]
Closed by #277.
