### ISSUE TITLE
Split conditions and annotate 

### ISSUE THREAD

**Issue by feanaros** [SingleR-inc/SingleR#278]
Hello team
I would like to split my dataset by condition and annotate the cell types using SingleR. Is there a way to visualize or compare the differences in cell type annotations between the two conditions?

**Comment by j-andrews7** [comment]
There is no need to split anything given each cell is annotated
individually. See the OSCA book for methods of differential
abundance/proportion testing of cell types.

**Comment by feanaros** [comment]
Hi, thank you. I know the differential proportion tests. 
Anyway, there is a way to visualize/quantify the proportion of cells assigned to the various types **in the same dataset**? Or should I refer just to the scores?

**Comment by j-andrews7** [comment]
Tons of ways. Take a look at dittoSeq for a few options for proportion
plots.
