### ISSUE TITLE
Bioc devel version: Expecting an external pointer: [type=list]

### ISSUE THREAD

**Issue by bbimber** [SingleR-inc/SingleR#279]
Hello,

Our CI includes jobs to run against the development bioconductor devel branch. Recently this began to fail for basic SingleR usage with the error "Expecting an external pointer: [type=list]". Is there any sort of incompatibility you are aware of?

I understand devel is not guaranteed to be stable. I'm just reporting this in case there is some issue that will appear in future releases. 

Thanks

**Comment by LTLA** [comment]
Oops. Thanks for spotting this, fixed in 2.7.5.

**Comment by bbimber** [comment]
Thanks for the fast fix. I assume it takes a day or so for this to filter into bioconductor's build process?

**Comment by dtm2451** [comment]
I think you should see it already by tomorrow's report.

Based on post timings here, and the reported timings [here](https://www.bioconductor.org/checkResults/) (top bullet seems like the relevant one to me), I think this should make it into today's devel build-tests --> tomorrow's reports.  Aaron commented well before 2pm East Coast time.  My understanding is that the devel build system pulls the latest from all packages' bioconductor git remotes at the start of the build process, and I don't believe your package needs to wait for a successful build of dependencies in a previous build at all; that instead, everything just tests with whatever the current state of all package gits were a pull-time.

**Comment by dtm2451** [comment]
Oops, forgot you are asking for CI tests, and not a package also in Bioc the devel system.  But same logic... the build for SingleR-dev will receive the code and version update in today's build.  Then triggered by the version bump Aaron did throw in (*assuming it successfully builds/tests), it will be propagated as the new current version within the same bioc build system run.  --> Your CI job should be able to pick up the new version by tomorrow!

**Comment by bbimber** [comment]
Perfectly fine by me, thanks again for the rapid fix.
