### ISSUE TITLE
Can SingleR work with a Xenium object?

### ISSUE THREAD

**Issue by jbrandst7** [SingleR-inc/SingleR#280]
I was hoping to use SingleR annotations as a way to standardize my analysis of cell identities across Xenium samples by using a 'master' Seurat object of scRNAseq data from many samples where I already provided detailed labels for rare cell populations. Can this be done with SingleR? Is there any way I should modify the xenium object in Seurat before it can be used as the test sample? Do you have any example code you could share? Thanks for any help you can provide!

**Comment by j-andrews7** [comment]
Read the README and/or [book](https://bioconductor.org/books/devel/SingleRBook/). 

>SingleR() is made to be workflow/package agnostic - if you can get a matrix of normalized counts, you can use it. `SingleCellExperiment` objects can be used directly. Seurat objects can be converted to `SingleCellExperiment` objects via Seurat's `as.SingleCellExperiment()` function or their normalized counts can be retrieved via `GetAssayData` or `FetchData`.
