### ISSUE TITLE
test and ref in the function SingleR

### ISSUE THREAD

**Issue by jianhaizhang** [SingleR-inc/SingleR#284]
Hello SingleR developers, 

I am interested in using your SingleR package to annotate my single cell data and have the following questions: 

1. When using the function SingleR, if my test and ref are from two independent studies. Should I jointly normalize both before running this function? 

2. In the help file, it says the ref should be log-transformed. Does it mean first normalized then log-transformed?

3. Should the test be normalized then log-transformed or just raw count?

Thank you in advance.

**Comment by LTLA** [comment]
> When using the function SingleR, if my test and ref are from two independent studies. Should I jointly normalize both before running this function?

No, that's not necessary.

> In the help file, it says the ref should be log-transformed. Does it mean first normalized then log-transformed?

For RNA-seq, yes. For microarrays, the order is less well-defined - I believe most array normalization methods operate on intensities that are already log-transformed.

> Should the test be normalized then log-transformed or just raw count?

Either is fine for the purposes of `SingleR::SingleR()`, which only cares about the ranks of values within each cell. Simple log-transformation and/or scaling normalization does not change these ranks. IIRC the only function that expects log-transformed _test_ matrices is `plotMarkerHeatmap()`.

**Comment by jianhaizhang** [comment]
Thanks a lot for the explanation.

**Comment by jianhaizhang** [comment]
Thanks a lot for the explanation.
